package com.ticket.cliente.entidades;
// Generated 20 nov. 2020 13:39:36 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCliente;
	private String apellido;
	private String nombre;
	private String cedula;
	private Date fechaContrato;
	private Integer estado;
	private Set ticketClientes = new HashSet(0);

	public Cliente() {
	}

	public Cliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(int idCliente, String apellido, String nombre, String cedula, Date fechaContrato, Integer estado,
			Set ticketClientes) {
		this.idCliente = idCliente;
		this.apellido = apellido;
		this.nombre = nombre;
		this.cedula = cedula;
		this.fechaContrato = fechaContrato;
		this.estado = estado;
		this.ticketClientes = ticketClientes;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public Date getFechaContrato() {
		return this.fechaContrato;
	}

	public void setFechaContrato(Date fechaContrato) {
		this.fechaContrato = fechaContrato;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public Set getTicketClientes() {
		return this.ticketClientes;
	}

	public void setTicketClientes(Set ticketClientes) {
		this.ticketClientes = ticketClientes;
	}

}
