package com.ticket.cliente.entidades;
// Generated 20 nov. 2020 13:39:36 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados implements java.io.Serializable {

	private int idEstado;
	private String estado;
	private Set ticketClientes = new HashSet(0);

	public Estados() {
	}

	public Estados(int idEstado, String estado) {
		this.idEstado = idEstado;
		this.estado = estado;
	}

	public Estados(int idEstado, String estado, Set ticketClientes) {
		this.idEstado = idEstado;
		this.estado = estado;
		this.ticketClientes = ticketClientes;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getTicketClientes() {
		return this.ticketClientes;
	}

	public void setTicketClientes(Set ticketClientes) {
		this.ticketClientes = ticketClientes;
	}

}
