package com.ticket.cliente.entidades;
// Generated 20 nov. 2020 13:39:36 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Prioridades generated by hbm2java
 */
public class Prioridades implements java.io.Serializable {

	private int idPrioridad;
	private String prioridad;
	private Set ticketClientes = new HashSet(0);

	public Prioridades() {
	}

	public Prioridades(int idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public Prioridades(int idPrioridad, String prioridad, Set ticketClientes) {
		this.idPrioridad = idPrioridad;
		this.prioridad = prioridad;
		this.ticketClientes = ticketClientes;
	}

	public int getIdPrioridad() {
		return this.idPrioridad;
	}

	public void setIdPrioridad(int idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public String getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public Set getTicketClientes() {
		return this.ticketClientes;
	}

	public void setTicketClientes(Set ticketClientes) {
		this.ticketClientes = ticketClientes;
	}

}
